version: "3.4"

services:
  searcher:
    build: ./searcher
    container_name: searcher
    env_file:
      - ./searcher/.env
    ports:
      - "5000:5000"

  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    env_file:
      - ./elasticsearch/.env
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data

volumes:
  elasticsearch-volume:
    driver: 'local'