version: "3.4"

services:
  # App
  searcher:
    build: ./searcher
    container_name: searcher
    env_file:
      - ./searcher/.env
    ports:
      - "5000:5000"

  # RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    restart: always
    tty: true
    image: rabbitmq:management
    ports:
      - "5672:5672"    # standard AMQP protocol port
      - "15672:15672"  # HTTP management UI
    environment:
      - ./rabbitmq/.env
    volumes:  # データを永続化
      - rabbitmq-volume:/var/lib/rabbitmq

  # ElasticSearch
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    env_file:
      - ./elasticsearch/.env
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data

volumes:
  rabbitmq-volume:
    driver: 'local'
  elasticsearch-volume:
    driver: 'local'